name: Mochinotch
options:
  bundleIdPrefix: dev.sleeeppy
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.0"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CODE_SIGN_STYLE: Manual
    CODE_SIGN_IDENTITY: "-"
    ENABLE_HARDENED_RUNTIME: NO
targets:
  Mochinotch:
    type: application
    platform: macOS
    sources:
      - path: Mochinotch
        excludes:
          - Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.sleeeppy.mochinotch
        PRODUCT_NAME: Mochinotch
        MARKETING_VERSION: "0.2.0"
        CURRENT_PROJECT_VERSION: "2"
        INFOPLIST_FILE: Mochinotch/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/../Frameworks"
        OTHER_LDFLAGS:
          - "-lsqlite3"
    dependencies:
      - sdk: ScreenCaptureKit.framework
